### PR TITLE
hack the tower - get test "passing" and start investigate what src and target AST needed

### PR DESCRIPTION
**Pull request by nico78**
see commented stuff in the macros file for structure

### CODE REVIEW

**Comment by fommil** [comment]
:smile:

**Comment by fommil** [comment]
great stuff! Thanks for this. I'll try to write up some of the goals of this project in more detail later today in the README and ping you. I think the hack day really helped to solidify what I hadn't verbalised before. Something like:

Macros and compiler plugins are becoming very popular in scala projects to reduce boilerplate, but the IDEs are unable to keep up (issuing many "false positive" errors). This results in a trade-off between reduced boilerplate and reduced functionality in your editor.

This project is an experiment in what breaks the presentation compiler (specifically whitebox macros, blackbox, compiler plugins) and will lay the foundation for a test framework aimed at macro/plugin authors to test their plugins in the presentation compiler (e.g. don't break the `RangePosition`s).

Plugin / macro authors may be able to fix their plugins in the best case, and provide a presentation compiler plugin in the worst case (e.g. to mock out the functionality of the real plugin / macro and issue a configurable warning where shortcuts are being taken, avoiding false negatives).

The conclusions of hack-the-tower are:

- basic whitebox macros break the presentation compiler, but work fine for the real compiler
- the above mission statement needed to be created

**Comment by nico78** [comment]
Hey, no problem - thanks for introducing me to ensime.  Mission statement
 looks good, think i get it now.
will try and get something actually working when i have a minute

**Comment by fommil** [comment]
btw, I think it's possible to get this to work in ensime with a flag that I didn't know about. I'll try later. I might actually look at this myself tonight.

**Comment by fommil** [comment]
(I'll try to look at different bits than you, if you're interested in this)

**Pull request merged**
